### ISSUE TITLE
Strange Error: Negative Size when creating Database

### ISSUE THREAD

**Issue by ch2994** [pmem/pmemkv-java#98] opened 2020-12-01 04:22 UTC
Not sure if this is a bug but it might be related to how I am using it. I am seeing the following error message when running the PictureExample.

Exception in thread "main" io.pmem.pmemkv.DatabaseException: [pmemkv_open] Failed opening pool: stat "/mnt/mem": negative size
        at io.pmem.pmemkv.Database.database_start(Native Method)
        at io.pmem.pmemkv.Database.<init>(Database.java:522)
        at io.pmem.pmemkv.Database.<init>(Database.java:27)
        at io.pmem.pmemkv.Database$Builder.build(Database.java:460)
        at PicturesExample.<init>(PicturesExample.java:91)
        at PicturesExample.main(PicturesExample.java:141)

I followed steps in this [blog](https://pmem.io/2016/02/22/pm-emulation.html) to emulate persistent memory on my Ubuntu machine and I mounted a file system called "/mnt/mem" on top of /dev/pmem0. Note that /dev/pmem0 has 4GB storage capacity.

Then I passed this "/mnt/mem" as path and 1073741824 as size to the PictureExample. What is strange is that if I change the engine type from "cmap" to "vcmap", the error is gone.

Can anyone please advise what might the root cause?

Thank you.

**Comment by lukaszstolarczuk** [comment] 2020-12-01 09:02
In this example `PmemkvPath` should be set to a database file (or a poolset file). This is because cmap engine requires file path (more on this, read [in pmemkv documentation](https://pmem.io/pmemkv/master/manpages/libpmemkv.7.html#cmap)). If you see for the configuration of a [vcmap engine](https://pmem.io/pmemkv/master/manpages/libpmemkv.7.html#vcmap), you'll see the directory path is required to configure that engine - this is why it works for you with vcmap.

Anyway, for more details about this example, see README file in the examples directory: https://github.com/pmem/pmemkv-java/tree/master/examples#picturesexample
There's a full command to run this (and other) example.

**Comment by ch2994** [comment] 2020-12-02 02:04
Thank you very much for your advice. I modified my code to pass in a file path and cmap mode worked. However, when I am doing stress testing with the following program, a modified version of StringExample. I am getting core dumped. The log did not show much; the only error message I am getting is `Aborted (core dumped)`. Looks like it is an error from the C code and I am not sure how to run gdb on the Java binding. 

Below is the program I am using that gives me the error. Note that this the modified  main function of StringExample; Rest of the StringExample is not touched.

----------------------------------------

   public static void main(String[] args) {
        String ENGINE = "cmap";

        System.out.println("Starting engine");

        Database<String, String> db = null;
        try{
                db = new Database.Builder<String, String>(ENGINE)
                        .setSize(1073741824)
                        .setPath("/mnt/mem/database1")
                        .setKeyConverter(new StringConverter())
                        .setValueConverter(new StringConverter())
                        .setForceCreate(true)
                        .build();
        }
        catch(DatabaseException e){
                db = new Database.Builder<String, String>(ENGINE)
                           .setSize(1073741824)
                           .setPath("/mnt/mem/database1")
                           .setKeyConverter(new StringConverter())
                           .setValueConverter(new StringConverter())
                           //.setForceCreate(true)
                           .build();
                           int count = 0;
        }
          
        String tempKey = "keyss" + count;
        db.put(tempKey, "value1");
        System.out.println("Putting new key total : " + db.countAll());
        count++;
  }

**Comment by ch2994** [comment] 2020-12-02 02:28
I was expecting to see out of memory exception. I have no clue where the above error came from.

**Comment by karczex** [comment] 2020-12-02 12:44
@ch2994  
Please provide detailed information about your system configuration:

    pmemkv-java version(s):
    pmemkv version(s):
    libpmemobj-cpp version(s):
    PMDK (libpmem/libpmemobj) version(s):
    OS(es) version(s):
    java/JDK versions:
    kernel version(s):

Did you install pmemkv/libpmemobj++/pmdk from distribution, or build it yourself? 
If you built kernel from sources, please provide also your configuration file.

**Comment by ch2994** [comment] 2020-12-02 19:43
Hello,

Thank you for the prompt reply.

Below is the requested information.

- pmemkv-java version(s): Version 1.0
- pmemkv version(s): Version 1.3
- libpmemobj-cpp version(s): Version 1.11
- PMDK (libpmem/libpmemobj) version(s): Version 1.10
- OS(es) version(s): 
     Distributor ID: Ubuntu
     Description:    Ubuntu 18.04.1 LTS
     Release:        18.04  
     Codename:       bionic
- java/JDK versions:
    openjdk version "1.8.0_275" 
    OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
    OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
-  Kernel version: Linux version 4.15.0-121-generic (buildd@lgw01-amd64-034) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020

For pmemkv/libpmemobj++ installation, we followed the step by step instruction from the [Install on Ubuntu](https://github.com/pmem/pmemkv/blob/master/INSTALLING.md#installing-on-ubuntu) part.

The pmemkv-java is working for us for the most parts. It is just this core dump thing I have no idea where it is coming from. If you need anything else from us, please let us know.

Thanks
Cheng

**Comment by karczex** [comment] 2020-12-04 15:34
Unfortunately I cannot reproduce your problem. 
If you use emulated pmem, please provide your kernel cmdline and dmesg output. Also coredump file may be usable. 

According to your example - I suggest to wrap while statement into try-catch, and call db.stop() at the end of application. 
```java
try {
       int count = 0;
       while(true){
           String tempKey = "keyss" + count;
            db.put(tempKey, "value1");
            System.out.println("Putting new key total : " + db.countAll());
            count++;
       }
} catch(DatabaseException e) {
...
}
db.stop()
```
If this doesn't help  I suggest you to try on Ubuntu 20.04 with libpmemkv-dev, and its dependencies installed using apt.

**Comment by lukaszstolarczuk** [comment] 2020-12-17 11:14
Hi @ch2994, can you please update status of this issue - did karczex ideas help you?

**Comment by lukaszstolarczuk** [comment] 2021-01-20 08:39
Quite some time passed I hope the issue is no more a problem. I'm closing this.
If you still encounter this or any other problem, please file a new issue.

**Closed by lukaszstolarczuk** 2021-01-20 08:39 UTC
Labels: Type: Question
